spring:
  datasource:
    jdbc-url: jdbc:log4jdbc:mariadb://svc.sel5.cloudtype.app:30204/songJava
    #    jdbc-url: jdbc:mariadb://svc.sel5.cloudtype.app:30204/songJava
    username: root
    password: mysql
    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
#    driver-class-name: com.mysql.cj.jdbc.Driver

# logback 위치 지정
logging:
  config: classpath:logback/logback-default.xml