server:
  port: 9000

spring:
  datasource:
    jdbcUrl: jdbc:log4jdbc:mariadb://svc.sel5.cloudtype.app:30204/songJava?allowMultiQueries=true
    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
    #    jdbcUrl: jdbc:mariadb://svc.sel5.cloudtype.app:30204/songJava
    #    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: mysql
  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp

# logback 위치 지정
logging:
  config: classpath:logback/logback-default.xml