spring:
  datasource:
    jdbcUrl: jdbc:log4jdbc:mariadb://svc.sel5.cloudtype.app:30204/songJava?allowMultiQueries=true
    #    jdbc-url: jdbc:mariadb://svc.sel5.cloudtype.app:30204/songJava
    username: root
    password: mysql
    #    driver-class-name: com.mysql.cj.jdbc.Driver
    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
  mvc:
    view:
      suffix: .jsp
      prefix: /WEB-INF/views/

# logback 위치 지정
logging:
  config: classpath:logback/logback-default.xml